### ISSUE TITLE
Breakpoints in files other than the one where we launch the debugger

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [rocky/emacs-dbgr#100]
Say I have a Python script and a Python module organized as follows:

```
├── main.py
└── my_package
    ├── __init__.py
    └── module.py
```

where **`main.py`** invokes functions from **`module.py`**. 

I would like to run the debugger until it hits a **breakpoint** in **`module.py`**. 

How do I do it?

----
I know I can get the debugger on **`main.py`** started via the usual  `M-x realgud:ipdb`  `RET` `ipdb /path/to/main.py` `RET` using the following script in my `PATH`
 ```
#!/bin/bash
/Users/amelio/anaconda/bin/ipython -c "%run -d $@"
```

Now comes the complicated part. How do I set up a breakpoint in **`module.py`**?

**Comment by cpitclaudel** [comment]
(this seems to be an IPDB question more than a RealGUD question, right?)

If you know which function will be called, you can use the `break <function_name>` command. Looking at the PDB docs, there doesn't seem to be a way to break at any time the other module is entered, however.

Does this help?

**Comment by amelio-vazquez-reina** [comment]
Thanks @cpitclaudel 

Doesn't RealGUD allow one to specify breakpoints on a buffer directly by pressing `b` on the location where we want a breakpoint? I asked this question hoping that one could do the same (in a file called by the main file)

The problem I have is that, if I start the debugger on *`main.py`* I can't just navigate and use `b` to leave breakpoints on lines in `module.py` (when I do so, it just inserts the letter `b`).

**Comment by rocky** [comment]
See issue #36 for an explanation of associating source-code buffers with the debugger process. This probably should be put on the wiki. 

Which reminds me @amelio-vazquez-reina how is that wiki entry going on the last problem you asked about?

**Comment by amelio-vazquez-reina** [comment]
Thanks @rocky I have been collecting these notes in [this relatively popular Question](http://stackoverflow.com/q/16867347/283296) that I asked (and [the answer](http://stackoverflow.com/a/23388116/283296) that I also wrote) in  StackOverflow. I was hoping to have a bit more experience with RealGUD before contributing to the repo, but you are right :) I should start taking collected the same notes here, so I started [this article](https://github.com/rocky/emacs-dbgr/wiki/ipdb-notes). Please feel free to edit/amend as needed :)

**Comment by cpitclaudel** [comment]
@amelio-vazquez-reina Thanks, I understand what you meant now. I'll admit to being pretty new to RealGUD as well, so I defer to @rocky on these matters :) Thanks very much for your contribution to the wiki, and for adding RealGUD to that stackoverflow question!

**Comment by cpitclaudel** [comment]
#104 implemented support for this; let's wait for confirmation that it works and then @amelio-vazquez-reina can close this :)

**Comment by amelio-vazquez-reina** [comment]
This is now done and documented in the Wiki on [the instructions regarding "short-key mode"](https://github.com/rocky/emacs-dbgr/wiki/How-to-Use#short-key-mode). Thanks @cpitclaudel!

**Comment by cpitclaudel** [comment]
And thanks @amelio-vazquez-reina for testing :)
