### ISSUE TITLE
Cannot Enter Debugger with C-c C-c

### ISSUE THREAD

**Issue by nordlow** [rocky/emacs-dbgr#108]
After recent update to version elpa/realgud-20160528.1724

`M-x realgud:gdb` with a ELF-file with debug information

followed by hitting `C-c C-c` in the buffer `*gdb shell*`

no longer splits current window into a
- gdb command prompt and 
- interactive read-only source window at current breakpoint

Instead only message

`That's all folks.... aborted (SIGINT)`

is given and the process executed in the buffer `*gdb shell*` is finished with error status.

What's wrong?

**Comment by cpitclaudel** [comment]
Hi @nordlow,

Does this happen with every file? Or just a specific input file? (If the latter, can you provide an example?)

Thanks!

**Comment by nordlow** [comment]
It happens with ELFs compiled from C/C++ (compiled with gcc 5.3.1) and D (using latest stable D compiler).

**Comment by rocky** [comment]
The thing that is suspicious is the message `That's all folks.... aborted (SIGINT)`

"That's all folks..." is not a message gdb issues. It is a message I use in many of my debuggers. So on invocation, I think you  are not running "gdb" bu something else? `realgud:cmdbuf-info-describe` will show what debugger command was run; make sure it is gdb.

**Comment by cpitclaudel** [comment]
@rocky My guess is that "That's all folks" is the message that realgud issues after gdb terminates. For example if I press q to exit GDB I get "That’s all folks.... finished".

@nordlow: Did `C-c C-c` use to do something different? Currently C-c C-c sends a signal to the debugger, which could very well cause it to exit, depending on its configuration. It could just be that there was a keybinding change.

Are you looking for `C-c S` maybe?

**Comment by nordlow** [comment]
My mistake. I forgot to prepend `"gdb "` to the first parameter of `realgud:gdb`.

**Comment by rocky** [comment]
> Is it possible to programmatically in elisp insert a set of GDB commands into the GDB  command-buffer at the startup

I think the `-x` and `-ex` options are what you want. From `man gdb`: 

      -command=file
       -x file
           Execute GDB commands from file file.

       -ex command
           Execute given GDB command.

See also https://sourceware.org/gdb/onlinedocs/gdb/Startup.html#Startup

As for the mistake, it happens. I've noticed that lots of people who use debuggers make mistakes.

**Comment by nordlow** [comment]
Thanks!
