### ISSUE TITLE
File name completion in "Run XXX (like this):" minibuffer prompt

### ISSUE THREAD

**Issue by birkenfeld** [rocky/emacs-dbgr#37]
For `M-x gdb`, I can complete the file name of the executable to run in the minibuffer with TAB. It would be nice if the same worked for the various `M-x realgud:xxx` commands.

**Comment by rocky** [comment]
Alas, I'm not seeing this behavior either.  For example, when I run `realgud:gdb" and then ask for help on the bindings, I see among other binds the below: 

```
Major Mode Bindings:
key             binding
---             -------

C-g		minibuffer-keyboard-quit
TAB		comint-dynamic-complete-filename
C-j		exit-minibuffer
RET		exit-minibuffer
ESC		Prefix Command
<C-tab>		file-cache-minibuffer-complete
<XF86Back>	previous-history-element
<XF86Forward>	next-history-element
<down>		next-history-element
<next>		next-history-element
<prior>		previous-history-element
<up>		previous-history-element
```

Is it not the case that `<TAB>` is set to *comint-dynamic-complete-filename* for you? 

If not cut and paste and maybe put in a gist somewhere what the bindings on the odd chance that will lead us to what's going wrong.

**Comment by birkenfeld** [comment]
Strange indeed. I looked at the source and can see that the minibuffer keymaps are defined very similarly. For some reason, in my configuration the `comint-dynamic-complete-filename` stays in the gud map, but not in the realgud map. I'll investigate further.

**Comment by birkenfeld** [comment]
I can confirm this is due to a local misconfiguration.
