### ISSUE TITLE
NodeJs setting breakpoints uses full paths 

### ISSUE THREAD

**Issue by fakedrake** [rocky/emacs-dbgr#41]
The node debugger doesn't understand full paths when setting breakpoints while `realgud:nodejs-set-break` sends absolute paths. This issue is [addressed](https://github.com/joyent/node/issues/7315) at the node repository since I think it would be better that this is solved on their side, but they seem to have neglected it so if there is a way to fix it on the realgud side that would be nice aswell.

**Comment by rocky** [comment]
How much work are you willing to put into this?

**Comment by rocky** [comment]
As you mentioned this is a problem with nodejs's debugger.

**Comment by rocky** [comment]
@timoshiu I sent you email related to this and nodejs. You got that, right?

**Comment by rocky** [comment]
@fakedrake I've forked nodejs into [trepanjs](https://github.com/rocky/trepanjs) and in git that now has a slightly hacky way of showing full paths.
