### ISSUE TITLE
realgud only has command buffer

### ISSUE THREAD

**Issue by jgarvin** [rocky/emacs-dbgr#42]
I installed the elpa package and invoked realgud:gdb. I got a command buffer, but that's it. I don't see anything different from what I would get manually invoking GDB inside a shell, and there's nothing in the documentation saying I should need to do more. I can manually type in the command to set a breakpoint, which works, and I see the extra output from annotate being set to one, but when I run and hit the breakpoint no window pops up with the source file on the line of the breakpoint like I would normally get with gud. Am I doing something wrong?

**Comment by rocky** [comment]
I introduced a bug which I've just addressed in commit 886f741 . Basically the common track mode wasn't getting entered when you ran gdb this way. You can tell if the track mode is getting set by seeing additional menu items in the tool bar and menu bar. You'll know if that mode is set if you see_ Realgud-Track_ (as well as _Realgud:GdbTrack_) in the list of minor modes. And _Debugger_ is in the menu bar.

**Comment by rocky** [comment]
Haven't heard back so I'll assume this is fixed.
