### ISSUE TITLE
Breakpoint circle in margin gets overwritten by line numbering

### ISSUE THREAD

**Issue by jgarvin** [rocky/emacs-dbgr#44]
I use linum-relative (https://github.com/coldnew/linum-relative) to display cursor-relative line numbers that update every time the cursor moves. Since this also uses the left margin when I move my cursor the red circle marker gets blown away. It'd be nice if the circle would be displayed before/after the number so I can have all the info on the left side. Offering a customization option to put the marker in the right margin could technically work but source code tends to be biased to the left side of the screen.

**Comment by cpitclaudel** [comment]
#101 moved breakpoint markers to the fringe, where they don't negatively with line numbers anymore :tada:.
