### ISSUE TITLE
Not possible to connect to pdb debugger started via non-'pdb' command

### ISSUE THREAD

**Issue by kotfic** [rocky/emacs-dbgr#46]
Celery and several other threaded applications make pdb style debugging available over telnet/sockets (see: http://celery.readthedocs.org/en/latest/tutorials/debugging.html) 

gud.el  currently supports connecting to these by changing the command run from ```pdb /path/to/file.py```  to ```telnet localhost 6900```

this crashes because localhost is expanded by ```pdb-parse-cmd-args```. Is this fixable,  and/or is there a reasonable workaround?

**Comment by rocky** [comment]
In the branch pdb-remote, I added interactive command `realgud:pdb-remote` replaces pdb-parse-cmd-args with another function. 

I haven't tested any of this out, and have no interest in furthering the use of *pdb* which in my opinion is ugly in more than one way. So view this more as a starting point for how one might do this. Feel free make and implement other possibilities.

**Comment by kotfic** [comment]
Thanks for the pointer,  trepan is great,  unfortunately celery implements pdb in their util/contrib folder so short of a PR over there i'm stuck.

**Comment by rocky** [comment]
> short of a PR over there

Do everyone a service and issue a pull requst
