### ISSUE TITLE
Compiling from melpa fails in require-relative-list

### ISSUE THREAD

**Issue by VladimirAlexiev** [rocky/emacs-dbgr#47]
I tried to install `realgud  20150719.1657` from melpa (NOT melpa-stable).
On I got a bunch of errors in the Compile-Log:

Compiling file c:/my/.emacs.d/elpa/realgud-20150719.1657/realgud.el at Thu Jul 30 08:48:17 2015
Entering directory c:/my/.emacs.d/elpa/realgud-20150719.1657/
realgud.el:105:1:Error: Cannot open load file: no such file or directory, c:/Emacs/share/emacs/24.5/lisp/progmodes/realgud/common/track-mode
Leaving directory c:/my/.emacs.d/elpa/realgud-20150719.1657/

In my case, that file is in `~/.emacs.d/elpa/realgud-20150719.1657/realgud/common/track-mode.el`.
If it's `require-relative-list`, why doesn't it look in the local dir but in `c:/Emacs/share/emacs/24.5/lisp/progmodes/` ?

**Comment by VladimirAlexiev** [comment]
The full log is in [this gist](https://gist.github.com/VladimirAlexiev/7331f59f6955e36f53fb)

**Comment by rocky** [comment]
When you installed [emacs-load-relative](https://github.com/rocky/emacs-load-relative) were there errors? Try installing that from git and run the tests.

If the tests are okay, then there's a problem in now melpa is compiling everything, and possibly load-relative is not loaded inside your emacs. So after emacs-load-relative is installed, try opening up a new emacs with and explicitly load-library load-relative and see if melpa's compile works.

**Comment by VladimirAlexiev** [comment]
There are no errors compiling load-relative. I did `(load-library "load-relative)`, then reinstalled `realgud` and everything was ok.
So MELPA knows to install `load-relative` before `realgud`, but doesn't know to load it?

**Comment by rocky** [comment]
It should get that simply because there is an underlying load going on and it should have added that to the load-path.

**Comment by VladimirAlexiev** [comment]
load it -> load it properly.
It gets loaded because emacs doesn't complain that `(load-relative)` is undefined. But somehow it thinks it should look in the global dir, not locally.
