### ISSUE TITLE
Byebug support for Ruby

### ISSUE THREAD

**Issue by rranelli** [rocky/emacs-dbgr#48]
I'm interested in using emacs-dbgr with the [byebug](https://github.com/deivid-rodriguez/byebug) debugger for Ruby. Byebug is newer and has better support for Ruby 2+.

I will probably try doing this myself in the next couple of days. Looks related to #39.

**Comment by rocky** [comment]
Great! It shouldn't be that hard. I

There are already something like 19 other debuggers, including about 4 ruby debuggers. So it's not like this is uncharted waters. Furthermore, I've documented [the process I use](https://github.com/rocky/emacs-dbgr/wiki/How-to-add-a-new-debugger).

**Comment by rranelli** [comment]
Thanks @rocky, I will keep you posted about my progress!

**Comment by rocky** [comment]
@rranelli I've just created [something for pry as a separate git repo](https://github.com/rocky/realgud-pry). Perhaps that could adapted for byebug.
