### ISSUE TITLE
JDB: too many arguments passed to realgud:run-process

### ISSUE THREAD

**Issue by jordonbiondo** [rocky/emacs-dbgr#51]
in `jdb.el`, 6 arguments are being passed to `realgud:run-process`, but in `run.el`, `realgud:run-process` is written to only accept a maximum of 5. This causes an error when trying to use `realgun:jdb`.

https://github.com/rocky/emacs-dbgr/blob/master/realgud/debugger/jdb/jdb.el#L87-L89

**Comment by rocky** [comment]
Thanks. 7edc244 should address. But I note that jdb support is piss poor. It would take as much effort to write a new debugger as it would be to jump through the hoops to get jdb working better.
