### ISSUE TITLE
Cannot invoke gdb

### ISSUE THREAD

**Issue by kkilger** [rocky/emacs-dbgr#54]
Hi,

when trying to use realgud with gdb, it can't start gdb, saying "Error running command: gdb". I have gdb installed and the normal gdb mode via "M-x gdb" runs fine. It doesn't matter if I enter a full path or just "gdb" in the command line.

I tested on two different computers with emacs 24.5 and emacs 25.0.50. 

What am I doing wrong?

Best regards,
Kilian.

**Comment by rocky** [comment]
Switch to the buffer that start `*gdb ...` And look there for more information. 

Here is an example: 

    Mx realgud:gdb
    gdb1 foo.c
    
    Current directory: /tmp/
    Command: gdb1 foo.c
    (file-error "Searching for program" "No such file or directory" "gdb1")
     Failed to invoke debugger gdb on program gdb1 with args foo.c

If it is not clear what the problem then is, cut and paste it as a comment just like I have done above.

**Comment by kkilger** [comment]
Hi rocky,
It seems that I didn't understood the concept of realgud at all. I still have to figure out how it works.

I use to debug a server application with 15 Mio. lines of code and 50.000 files. This application can't be started by emacs or gdb. So I tend to start gdb without any command line arguments and do an "attach pid" later on. This doesn't seem to work in realgud, i.e. I have to provide some arguments to gdb (why?). Okay, now I start with "gdb -p pid" (I configured the gdb command to be gdb --annotate 1). I then get a very beautiful gdb console. But how to attach a source buffer to it?

At the same time I get a "cannot find command buffer for pid" error message in the status bar. If I go the a source buffer and invoke "realgud:cmd-break" I also get the error message "cannot find command buffer for foo.c". At the same time, realgud creates and empty buffer with name "pid".

Best regards,
Kilian.

**Comment by rocky** [comment]
> I have to provide some arguments to gdb (why?). 

The script name is used in customizing the command buffer name. With more work and coding I think this could be worked around.  Feel free to come up with a patch. I guess _realgud:gdb_ of `realgud/debugger/gdb/gdb.el` is where you'd start. 
Or open this as a separate issue so it can be tracked separately.

> But how to attach a source buffer to it?

Use `realgud:cmdbuf-associate`, but also see issue #53 for quirks in that. 

As for the rest, if you want issues to get fixed, make small test cases that exhibit the problem and submit them as individual issues.
