### ISSUE TITLE
Using gdb with "-p <pid>" option, creates new buffer with name <pid>

### ISSUE THREAD

**Issue by kkilger** [rocky/emacs-dbgr#57]
When invoking realgud:gdb with command "-p pid", where "pid" is a process id, a new empty buffer with name "pid" is created.

**Comment by rocky** [comment]
A priori,  I don't see anything wrong with this. Each debugger process has a command buffer. So each one needs a unique name. 

You bug reports are a bit vague. Please follow the following process. First create the smallest test case that exhibits the problem. Give what you tried as exactly as you can. Cut and paste like I have been previously. Then give exactly what you got.  Again cut and paste. Then describe what you think should happen. 

Thanks.

**Comment by kkilger** [comment]
Hi rocky,
I don't talk about the *gdb pid shell* buffer. There are two buffers created!

Procedure: 
M-x realgud:gdb
gdb -p 4346

C-x b <tab>
Two new buffers: 4346 and *gdb 4346 shell*

Regards,
Kilian.
