### ISSUE TITLE
Expansion of file name via %X is not working in realgud:gdb

### ISSUE THREAD

**Issue by kkilger** [rocky/emacs-dbgr#58]
I start realgud:gdb with attaching to a process id and automatically assigning the source buffers, via the following code snippet (using -filter from dash.el):

```
(defun my-find-command-buffer (pid)  
  "Find the current command buffers for the given pid."
  (-filter (lambda (buf)
             (and
              (string-prefix-p (concat "*gdb " (number-to-string pid)) (buffer-name buf))
              (get-buffer-process buf))) (buffer-list)))

(defun my-start-debugging-pid (pid)
  "Start debugging process with pid PID."
  (interactive "nEnter the pid: ")
  (let* ((cW (selected-window)))
    (if (one-window-p)
        (select-window (split-window-horizontally))
      (other-window 1))
    (realgud:gdb (concat realgud:gdb-command-name " -p " (number-to-string pid)))
    (select-window cW)
    (mapc (lambda (buf)
            (realgud:cmdbuf-associate (buffer-name buf))) (my-find-command-buffer pid))))`
```
This works great. Afterwards setting and removing breakpoints via realgud:cmd-break and realgud:cmd-clear does not work, because the file name (seems to be %X in the source code) is not expanded and only the line number is given to gdb.

Defining realgud:cmd-break like follows:
```
(defun my-realgud:cmd-break()
  "Set a breakpoint at the current line"
  (interactive)
  (realgud-send-command (concat "break " (buffer-file-name) ":"
                                (number-to-string (line-number-at-pos)))))
```
does work (similar for clear), but the breakpoint is then not cleared from the UI anymore (of course).

Why is the %X not expanded?

**Comment by rocky** [comment]
The problem wasn't that %X wasn't expanded. It just wasn't specified. In commit 2facb99 this is fixed. In that commit I have also adapted some of the code you gave. I'll probably change `realgud:gdb-pid-associate` to make sure that the source buffer is visible after running. 

The window layout in implied by `my-start-debugging-pid()` is a bit too specific for general use. If this is what you want for yourself, that's great but I'd suggest making use of the routines just added as they are possibly more precise.
