### ISSUE TITLE
Invoking realgud:gdb without command line arguments does not work

### ISSUE THREAD

**Issue by cohomology** [rocky/emacs-dbgr#59]
Invoking realgud:gdb without command line arguments should either:

  a) work
  b) give some meaningful error message

At the moment, it gives a "Wrong type argument: stringp, nil" error.

**Comment by rocky** [comment]
Ok. Suggest a patch.

**Comment by kkilger** [comment]
Hi rocky,
I will try it. But I can't promise anything. I started using emacs 2 weeks ago (coming from vim), so although Lisp might be easy, I don't know anything about how things are done correctly. Kilian.

**Comment by rocky** [comment]
I'm sure you'll do fine.
