### ISSUE TITLE
Compiling realgud locally is not possible

### ISSUE THREAD

**Issue by cohomology** [rocky/emacs-dbgr#64]
I can byte-compile realgud via ./configure + make without problems when its dependencies (list-utils, etc.) are installed globally, e.g. in /usr/local/share/emacs/site-lisp. 

But when they are not available globally, but locally in my init.el's load path, they are not found by the configure script.

Is this by design or is there some workaround for that?

**Comment by rocky** [comment]
No global emacs package as far as I know is sensitive to the current load-path that is dynamically set in emacs. And how could it? 

As suggested by `./configure --help` you can always set `EMACSLOADPATH` before running it. So possibly way of getting `EMACSLOADPATH` to match the current value of `load-path` is to run the `./configure` from inside emacs in such a way that it will set EMACSLOADPATH before running `./configure`.  

Going one step even more complicated. You could run a command the loads `init.el` if you know that is all that is needed to set up `load-path` and then have emacs somehow issue the configure command after setting `EMACSLOADPATH`.

**Comment by cohomology** [comment]
Your last sentence is exactly what I want. For the best, some ```--with-local``` option for the configure script, which automatically invokes emacs and sets the corresponding environment variable transparently for the user. After that, ```make``` and ```make check``` should be possible, but not ```make install```.

I was just wondering how emacs is invoked currently in the ```configure``` script _without_ loading init.el? If we could just trick him to follows its normal procedure (e.g. starting up, __with__ loading ```init.el```). But I guess compile times would increase by the factor of 1000 then (at least with my ```init.el``` ;-) )

I will look at this next week ...

**Comment by rocky** [comment]
https://github.com/rocky/emacs-dbgr/blob/master/configure.ac#L12-L18 is how emacs package checking works. https://github.com/rocky/emacs-dbgr/blob/master/test/Makefile.am#L59-L60 gives the command  to invoke a particular test. 

For more detail, there are two tools that I've written to help out. The bash debugger and the GNU make debugger.
