### ISSUE TITLE
Can't find bashdb and zshdb program if they are installed with --prefix (no root)

### ISSUE THREAD

**Issue by yu-yuxuan** [rocky/emacs-dbgr#69]
I install the bashdb and zshdb both without root. (That is  adding --prefix=$HOME) and then add into zshrc as alias
I can run it on the terminal.
But when I want to use zshdb and bashdb in emacs. It gets error

```
5-|Current directory: /aa/bb/
6-|Command: zshdb /aa/bb/p.sh
7-|(file-error "Searching for program" "Is a directory" "zshdb")
8-|Failed to invoke debugger zshdb on program zshdb with args /aa/bb/p.sh
```

**Comment by rocky** [comment]
Think this is a user problem not a zshdb or emacs problem. I think the deal is that *Emacs* doesn't know where zshdb is. 


To test this guess:  when you run `M-x zshdb` and it says "run zshdb like this", do you put in the full path to zshdb? 

When you evaluate in *scratch* `(getenv "PATH")`, do see the directory where `zshdb` is located?

**Comment by yu-yuxuan** [comment]
@rocky 
I replace the zshdb with full path and it works. 
Also, evaluate in scratch `(getenv "PATH")`, it didn't contain. 
Thank you

**Comment by rocky** [comment]
I don't understand what you mean. (I suspect English isn't your native language, and if that's the case, your understanding of English is far better than my understanding of your native language. Still, I don't understand you.)

I need to understand the steps you did, and more detailed output of what you got. Put in `.emacs` file `(setq debug-on-error 't)` and show the entire contents of the `[Backtrace]` buffer when there is a failure. 

As before I doubt this is a problem with package but more related to how to configure and use Emacs. So http://emacs.stackexchange.com/ may also be of help.

**Comment by yu-yuxuan** [comment]
@rocky Sorry for my poor English, what I mean is  that 
I fail to put the location  of bashdb and zshdb into `$PATH` although I alias it by using `alias bashdb=$HOME/bin/bashdb`. 
After I put bashdb and zshdb into `$PATH`, it worked. So this is solved. Thank you.

**Comment by rocky** [comment]
Good to hear that you have this working now.
