### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by nickenchev** [rocky/emacs-dbgr#72]
Is there any documentation listing commands/shortcuts on common things like:
toggle breakpoints
print values
print frame
etc

Please let me know if I'm not seeing it in the docs or I'm supposed to dig it up elsewhere.

Thanks

**Comment by rocky** [comment]
I might have written something somewhere. But you know you could always start something on the wiki for those things that you find helpful. As someone learning this you are probably in a better position to know what's most needed. Thanks.

**Comment by cpitclaudel** [comment]
@nickenchev, please have a look at https://github.com/rocky/emacs-dbgr/blob/new-README/README.md ; comments are very welcome!
