### ISSUE TITLE
Tab completion with ipdb

### ISSUE THREAD

**Issue by dwadden** [rocky/emacs-dbgr#75]
Hi,

First, thanks to whomever is working on implementing this. It's super helpful to have Python tab completion while debugging. 

The functionality isn't quite working for me. As a minimal example, I created an empty .py file and, from the buffer containing the file, invoked `realgud:ipdb`.

This correctly started an ipdb session. Then at the console I entered `x = [1,2,3]`. Next, I typed `x.` at the console. I expected tab completion to offer a list of available methods, but instead it gave this message in the minibuffer: `Marker does not point anywhere`. If I entered `x.a` for example, which should complete to `x.append`, I got: `[No matches]`. 

On the other hand, if I entered `x.` in the debugger and then evaluated the following elisp command in the minibuffer: `(realgud:ipdb-completion-at-point)`, the following shows as the result": `(nil 506 ("x.append" "x.count" "x.extend" "x.index" "x.insert" "x.pop" "x.remove" "x.reverse" "x.sort" :exclusive yes)`.

This seems like the right thing. So, somehow, the result from `ipdb-completion-at-point` isn't getting passed back to `completion-at-point` correctly.

Are you aware of some way to pass the result back to allow for tab completion?

Thanks,

Dave

**Comment by butala** [comment]
I have attempted to reproduce Dave's steps and had partial success. For me, emacs will hang as soon as I type `x.`.

I am also very interested in being able interact with ipdb directly from emacs. The pieces appear to be there, but are not connecting correctly (at least for Dave and I). Is there any further information I could provide that would help to debug this issue?

--- Mark

**Comment by rocky** [comment]
Just looked at this and tried it. I am getting the dwadden behavior: `Marker does not point anywhere`.  Commit 1716c8a addresses some of this but there still seems to be some cases where there is a single completion like `x.p` which needs more more. I've exhausted my patience on this. (If you want find a debug in the python trepan debuggers, I think I'd have more patience.) 

So for those who are interested in tools to track this down such as @batula may be interested here is what I then did. 

I evaluate `(setq debug-on-error 't)`. Then I see in `*Backtrace*` what happens on error. I get

```lisp
Debugger entered--Lisp error: (error "Marker does not point anywhere")
  <=(#<marker in no buffer> 110)
  (or (<= start (point)) (cl--assertion-failed (quote (<= start (point))) nil (list start (point)) (list)))
  (progn (or (<= start (point)) (cl--assertion-failed (quote (<= start (point))) nil (list start (point)) (list))) nil)
  completion-in-region(#<marker in no buffer> 110 ("x.append" "x.count" "x.extend" "x.index" "x.insert" "x.pop" "x.remove" "x.reverse" "x.sort") nil)
  (let* ((completion-extra-properties plist) (completion-in-region-mode-predicate (function (lambda nil (let ((newstart ...)) (and newstart (= newstart start))))))) (completion-in-region start end collection (plist-get plist :predicate)))
  (let ((plist x) (collection x) (end x) (start x) (hookfun x)) (if (markerp start) nil (setq start (copy-marker start))) (let* ((completion-extra-properties plist) (completion-in-region-mode-predicate (function (lambda nil (let (...) (and newstart ...)))))) (completion-in-region start end collection (plist-get plist :predicate))))
  (let* ((x (car x)) (x (cdr x))) (let ((plist x) (collection x) (end x) (start x) (hookfun x)) (if (markerp start) nil (setq start (copy-marker start))) (let* ((completion-extra-properties plist) (completion-in-region-mode-predicate (function (lambda nil (let ... ...))))) (completion-in-region start end collection (plist-get plist :predicate)))))
  (if (consp x) (let* ((x (car x)) (x (cdr x))) (let ((plist x) (collection x) (end x) (start x) (hookfun x)) (if (markerp start) nil (setq start (copy-marker start))) (let* ((completion-extra-properties plist) (completion-in-region-mode-predicate (function (lambda nil ...)))) (completion-in-region start end collection (plist-get plist :predicate))))) (funcall pcase-0))
  (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* ((x (car x)) (x (cdr x))) (let ((plist x) (collection x) (end x) (start x) (hookfun x)) (if (markerp start) nil (setq start (copy-marker start))) (let* ((completion-extra-properties plist) (completion-in-region-mode-predicate (function ...))) (completion-in-region start end collection (plist-get plist :predicate))))) (funcall pcase-0)))
  (if (consp x) (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* ((x (car x)) (x (cdr x))) (let ((plist x) (collection x) (end x) (start x) (hookfun x)) (if (markerp start) nil (setq start (copy-marker start))) (let* ((completion-extra-properties plist) (completion-in-region-mode-predicate ...)) (completion-in-region start end collection (plist-get plist :predicate))))) (funcall pcase-0))) (funcall pcase-0))
  (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* ((x (car x)) (x (cdr x))) (let ((plist x) (collection x) (end x) (start x) (hookfun x)) (if (markerp start) nil (setq start ...)) (let* (... ...) (completion-in-region start end collection ...)))) (funcall pcase-0))) (funcall pcase-0)))
  (cond ((functionp x) (let ((f x)) (funcall f))) ((consp x) (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* (... ...) (let ... ... ...)) (funcall pcase-0))) (funcall pcase-0)))) (t (funcall pcase-0)))
  (let* ((x (car res)) (x (cdr res))) (cond ((functionp x) (let ((f x)) (funcall f))) ((consp x) (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* ((x ...) (x ...)) (if (consp x) (let* ... ...) (funcall pcase-0))) (funcall pcase-0)))) (t (funcall pcase-0))))
  (if (consp res) (let* ((x (car res)) (x (cdr res))) (cond ((functionp x) (let ((f x)) (funcall f))) ((consp x) (let* ((x (car x)) (x (cdr x))) (if (consp x) (let* (... ...) (if ... ... ...)) (funcall pcase-0)))) (t (funcall pcase-0)))) (funcall pcase-0))
  (let* ((pcase-0 (function (lambda nil (if (cdr res) (progn (message "Warning: %S failed to return valid completion data!" ...))) (cdr res))))) (if (consp res) (let* ((x (car res)) (x (cdr res))) (cond ((functionp x) (let ((f x)) (funcall f))) ((consp x) (let* ((x ...) (x ...)) (if (consp x) (let* ... ...) (funcall pcase-0)))) (t (funcall pcase-0)))) (funcall pcase-0)))
  (let ((res (run-hook-wrapped (quote completion-at-point-functions) (function completion--capf-wrapper) (quote all)))) (let* ((pcase-0 (function (lambda nil (if (cdr res) (progn ...)) (cdr res))))) (if (consp res) (let* ((x (car res)) (x (cdr res))) (cond ((functionp x) (let (...) (funcall f))) ((consp x) (let* (... ...) (if ... ... ...))) (t (funcall pcase-0)))) (funcall pcase-0))))
  completion-at-point()
  funcall-interactively(completion-at-point)
  call-interactively(completion-at-point nil nil)
  command-execute(completion-at-point)
```

Ok. So I see this error is coming from `completion-in-region()` and then I can use edbug to set a breakpoint there. And the errors seems to be that `(point)` gives null. The function that is returning this is `realgud:ipdb-backend-complete` so I started edebug-ing that function too and that's what led me to the specific commit. To finish. 

```         (completion-in-region start end collection
                               (plist-get plist :predicate))))
``` 
of minibuffer.el is failing and I don't understand completion-in-region well enough to understand what it needs.  But this should be enough  information for ipdb users for others to pick off here and start invest

**Comment by cpitclaudel** [comment]
@rocky I think your commit fixed the `marker does not point anywhere` issue. As for `x.p` not getting completed, I think I know where this comes from: the `.` in `x.p` doesn't have the right syntax class in the command buffer, so `(bounds-of-thing-at-point 'word)` returns just `p` instead of `x.p`, and `completion-in-region` doesn't know how to complete `p` into `x.p` from that.

We can either fix the syntax table or find a way to get the prefix from IPDB, I think.

**Comment by cpitclaudel** [comment]
Turns out it was pretty easy to get the prefix from IPython; I made a PR to that effect.

**Comment by rocky** [comment]
Thanks!

**Comment by sphakka** [comment]
Is this really working?
With Emacs 26.2, I get

    completion--capf-wrapper: Symbol’s function definition is void: realgud:ipdb-completion-at-point
  
Completion *does* work in python-mode, as well as with ipython in a bash shell...

**Comment by rocky** [comment]
The function has been renamed `realgud--ipdb-complete-script` in version 1.0.0. 

Is it possible to adjust this from the caller `completion-capf-wrapper`?
