### ISSUE TITLE
byte-code: Invalid function: realgud-struct-field-setter

### ISSUE THREAD

**Issue by sukeyisme** [rocky/emacs-dbgr#78]
osx 10.11.4
emacs 24.5.1
when i M-x load-library  realgud then this error appear

**Comment by rocky** [comment]
I botched a release of load-relative whose __FILE__ function isn't working in the context spacemacs uses it via package_install. I've reinstated the old code in https://github.com/rocky/emacs-load-relative/commit/2aa165fba4a663fdaeda7f7e2cec38bad617ccd8

Sorry for the trouble.

**Comment by sukeyisme** [comment]
so what should i do,if i want to use your package now.

**Comment by rocky** [comment]
Either: 

* Use  load-relative from elpa not melpa. 
* Use github source for load-relative. 
* Use emacs-dbgr from github 

Wait for melpa to add another load-realtive (since the change is on github)

**Comment by sukeyisme** [comment]
thank you for your great package now it work fine.
