### ISSUE TITLE
Wrong number of arguments for setq

### ISSUE THREAD

**Issue by cpitclaudel** [rocky/emacs-dbgr#79]
In Emacs 25, RealGUD crashes on start with the following message:

```
Debugger entered--Lisp error: (wrong-number-of-arguments setq 3)
  signal(wrong-number-of-arguments (setq 3))
  realgud:track-from-region(182 #<marker at 238 in *pdb sphinx-build shell*> #<marker at 238 in *pdb sphinx-build shell*> #<buffer *pdb sphinx-build shell*> t t)
  realgud-track-comint-output-filter-hook("> /usr/local/bin/sphinx-build(4)<module>()\n-> import re\n")
  run-hook-with-args(realgud-track-comint-output-filter-hook "> /usr/local/bin/sphinx-build(4)<module>()\n-> import re\n")
  comint-output-filter(#<process pdb> "> /usr/local/bin/sphinx-build(4)<module>()\n-> import re\n")
  read-event(nil t 2)
  sit-for(2)
  execute-extended-command(nil "realgud:pdb")
```

This is due to this line:

```
(setq frame-num (realgud-track-selected-frame text) text)
```

Which indeed looks wrong :)

**Comment by cpitclaudel** [comment]
Just removing the extra "text" seems to work of; this debugger is really cool!

**Comment by rocky** [comment]
Hmm. I don't see this in the current github code. You are getting this from Melpa stable maybe? 

If that's the case, I guess I'll have to update that.

**Comment by cpitclaudel** [comment]
No, I just installed from MELPA. It's on https://github.com/rocky/emacs-dbgr/blob/cfe2be3d8851de6937da2a9f771e13280ecd60ce/realgud/common/track.el#L191

**Comment by rocky** [comment]
ok. Thanks for the info. 76cb0d4 should fix this. When it comes over MELPA and it works, just close the issue.

**Comment by cpitclaudel** [comment]
Brilliant, thanks!
