### ISSUE TITLE
RealGUD uses badly scoped keybindings

### ISSUE THREAD

**Issue by cpitclaudel** [rocky/emacs-dbgr#83]
From the [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html#Key-Binding-Conventions):

> Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.

> Changing all the Emacs major modes to respect this convention was a lot of work; abandoning this convention would make that work go to waste, and inconvenience users. Please comply with it.

This is probably non-trivial to fix, though. I noticed because RealGUD broke my own C-c bindings :/

**Comment by rocky** [comment]
From my standpoint this is a bad thing since I've got down C-c !! But I guess I'll adjust. 

And fixing this is probably not a binary thing, but commands can be changed as they are found. So make a suggestion and start. Is C-c C-c okay to use?

**Comment by cpitclaudel** [comment]
I think `C-c C-c` would be fine, but could be a bit misleading. Many modes use it to mean "compile", and shell-related modes tend to use it for "kill program" (so I'd expect `C-c C-c` to kill the program being debugged).

Indeed, fixing this isn't binary. We could transition away progressively (introduce and polish new bindings, and retire the previous ones after a long-ish while)

**Comment by cpitclaudel** [comment]
Amusingly, though, `edebug` uses `C-c C-c` to mean `go`, so there'd be precedent to do that too. In fact, we could draw some inspiration from `edebug-mode-map` (and I'm sure you already did, given that many of RealGUD bindings felt familiar :)

**Comment by rocky** [comment]
I probably looked at edebug-mode-map but that was a while ago and probably carefully enough.

Yes, please let's keep things like edebug where it make sense. One of the reasons I wrote all of the debuggers I have and realgud was to try to stop proliferation of gratuitously different command sets (at least that I would have to use.)

**Comment by cpitclaudel** [comment]
> Yes, please let's keep things like edebug where it make sense. One of the reasons I wrote all of the debuggers I have and realgud was to try to stop proliferation of gratuitously different command sets (at least that I would have to use.)

Yup, this is really great.

**Comment by cpitclaudel** [comment]
Here is one suggestion: currently, `e` is mapped to `eval region`, and "C-c e" to `eval`. What would you think of enhancing `e` so that it runs `eval-region` if a region is active, and `eval` otherwise? This would make `C-c e` virtually redundant, and it would be a convenient improvement, I think. As always, I'm happy to provide a patch.

**Comment by rocky** [comment]
Sure. That sounds great.

**Comment by cpitclaudel** [comment]
Done :)

**Comment by rocky** [comment]
Feel free to close issues when you feel they are ready to be closed.

**Comment by cpitclaudel** [comment]
Ok. I think this one is still dependent on cleaning up `realgud:cmd-remap` a bit, so I'll leave it open for now.

**Comment by cpitclaudel** [comment]
Completed in #98 :)
