### ISSUE TITLE
Are autoloads broken?

### ISSUE THREAD

**Issue by cpitclaudel** [rocky/emacs-dbgr#84]
Many files in the realgud tree seem to be defining autoloads, but the autoloads.el file that Emacs generates upon installing from MELPA is empty (I'm on Emacs 25).

There's a FIXME that looks relevant to this (?) in realgud.el:

```
;; FIXME: extend require-relative for "autoload".
(defun realgud:load-features()
```

**Comment by rocky** [comment]
I don't remember exactly, but the MELPA problem is that they look for (provide 'some-symbol) and I use (provide-me). 

I'm not changing all of the files to (provide 'some-symbol) as this is lame. The technology should somehow be fixed.

**Comment by cpitclaudel** [comment]
> I don't remember exactly, but the MELPA problem is that they look for (provide 'some-symbol) and I use (provide-me). 

Interesting. The problem would be in Emacs, not in MELPA, since Emacs is generating these autoloads, right? I'll look into it and open a bug report if needed.

> I'm not changing all of the files to (provide 'some-symbol) as this is lame. The technology should somehow be fixed.

Fair enough. On the other hand, the current situation for MELPA installs is that users need to either `load-library` or write autoloads by hand; this isn't ideal either.

**Comment by cpitclaudel** [comment]
I think I understand this now. Fundamentally, the issue just seems to be that `update-directory-autoloads` doesn't recurse into subdirs, and package.el doesn't call it on subdirectories of the package.

I'll start a thread on emacs-dev about this; the manual is at least misleading.

**Comment by cpitclaudel** [comment]
I wrote to emacs-devel; let's see what this yields.

Meanwhile, a solution could be to statically generate the autoloads for each subdirectory, and ship those; then in realgud.el we would have an autoloaded form that loads these autoload files. This would be rather simple.

**Comment by cpitclaudel** [comment]
Actually, we could do something simpler than my last suggestion. we could generate autoloads for all subdirectories in a realgud-additional-autoloads file, which we would load ourselves from an autoloaded form.

**Comment by cpitclaudel** [comment]
Here's a draft implementation:

```
;;;###autoload
(defconst realgud-subdir-autoloads-name "subdirectory-autoloads.el")

;;;###autoload
(defconst realgud-content-dir
  (file-name-directory
   (or (and load-in-progress load-file-name)
       (bound-and-true-p byte-compile-current-file)
       buffer-file-name
       (error "Can't guess content directory."))))

;;;###autoload
(with-demoted-errors "Error loading autoloads: %s"
  (load (expand-file-name realgud-subdir-autoloads-name realgud-content-dir) t t))

(defun realgud-refresh-subdirectory-autoloads ()
  "Update subdirectory-autoloads.el.
This is needed because the package.el infrastructure doesn't
process autoloads in subdirectories; instead we create an
additional autoloads file of our own, and we load it from an
autoloaded form."
  (interactive)
  (let ((generated-autoload-file
         (expand-file-name realgud-subdir-autoloads-name realgud-content-dir)))
    (when (file-exists-p generated-autoload-file)
      (delete-file generated-autoload-file))
    (dolist (name (directory-files-recursively realgud-content-dir "" t))
      (when (file-directory-p name)
        (update-directory-autoloads name)))))
```

Once this is saved to a file in the root directory of the realgud package, running the `realgud-refresh-subdirectory-autoloads` function creates a `realgud-subdirectory-autoloads.el` file (this is a step that we would do when new autoloads are introduced). Once that is there, generating package autoloads (as done by `package.el`) will pick up the call to load, and therefore every time the package is activated all autoloaded functions will be available.

Hopefully a better solution is available, but this seems rather lightweight. Opinions welcome :)

**Comment by rocky** [comment]
Seems reasonable to me.

**Comment by cpitclaudel** [comment]
Ok. I'll wait for discussion on emacs-devel, and prepare a PR after a while. It would be really neat to have realgud work out of the box on MELPA, with the lazy-loading that autoloads enable.

Do you envision any issues with autoloading, by the way? I notice that `realgud.el` calls `realgud:load-features`, which won't be called when a file is lazy-loaded. A quick look around doesn't suggest that this would be an issue, but double-checking is always good :)

**Comment by rocky** [comment]
Yeah, I think load-features was a workaround for autoloading not working. Since each file should pull in what it needs, with care, load-features should eventually be removed.
