### ISSUE TITLE
Something looks wrong with cmd-delete

### ISSUE THREAD

**Issue by cpitclaudel** [rocky/emacs-dbgr#87]
Here's the code:

```
(defun realgud:cmd-delete(&optional arg)
    "Delete breakpoint by number."
    (interactive "pBreakpoint number: ")
    (let* ((line-num (line-number-at-pos))
	   (arg (realgud-get-bpnum-from-line-num line-num)))
      (if arg
	  (realgud:cmd-remap arg "delete" "delete %p" "D")
	(message "Can't find breakpoint at line %d" line-num))
      )
    )
```

Some surprising things:

* the `arg` parameter is never used
* the interactive spec includes a prompt, but the "p" specifier doesn't prompt (instead, it just passes the current point)

It looks like what cmd-delete is really doing is a `clear`, although inferring a breakpoint number from the current line (which turns out to be a very useful feature in PDB, since PDB does print a proper deletion message when suppressing a breakpoint by number, and thus realgud tracks breakpoints properly). I'd argue that this is a much more useful feature than removing a breakpoint by number, so it does deserve a binding; but it's not entirely clear to me what the current difference is between `cmd-delete` and `cmd-clear` (maybe the current function should be renamed `cmd-clear-using-delete`, with the same (`d`) keybinding, and a new copy of delete that actually deletes a breakpoint by number could be introduced.

Alternatively, we could apply the C-u trick here as well (and same for -enable and -disable); without a prefix they would operate on the current line, and with a prefix they would prompt for a number.

**Comment by rocky** [comment]
In gdb and other debuggers there can be several breakpoints on a line. This can be useful if they have I guess different conditions associated with them. That I think was the _intent_ of  the arg. The implementation though is faulty. So in that sense, the intent it is not to remove all breakpoints (clearing) on a line. 

Sure use the C-u trick.

**Comment by cpitclaudel** [comment]
Thanks for the clarification. This sounds like an easy fix; I'll have a PR ready tomorrow I think.
