### ISSUE TITLE
Getting started with RealGUD and ipdb

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [rocky/emacs-dbgr#96]
I installed RealGUD  through MELPA and then followed these steps:

1. `M-x load-library realgud`
2. Then, on a Python buffer, I run `M-x realgud:ipdb`

The last step above prompts me with:

`Run ipdb (like this): ipdb <path_to_python_file>`

If I then do `RET`, I get:

`(file-error "Searching for program" "No such file or directory" "ipdb")`

I don't have `ipdb` in my `PATH` (I do have the latest IPython, Python, etc). I am not sure there is supposed to be a binary for `ipdb` (is it?)

Am I following these steps properly?

**Comment by rocky** [comment]
When it says `Run ipdb (like this):` the part after that is the command you would run from a command line to run like `run -d my_script` from your other question.

**Comment by amelio-vazquez-reina** [comment]
Thanks @rocky . `run -d` is actually a command that you run from _**within**_ `IPython`.

Seeing your point, I tried entering the following command on the prompt that i get from `M-x realgud:ipdb`:

`/Users/amelio/anaconda/bin/ipython -c "%run -d /Users/amelio/code/python_tests/quick_example.py"`

but I end up with:
```
  File "<ipython-input-1-6a8e051bcd87>", line 1
    Users(/amelio/code/python_tests/%run, -d, /Users/amelio/code/python_tests/quick_example.py)
```

However, if I do ``/Users/amelio/anaconda/bin/ipython -c "%run -d /Users/amelio/code/python_tests/quick_example.py"`from the command line (i.e. outside of Emacs), it works like a charm...

**Comment by rocky** [comment]
realgud parses your input and it's messing up badly here. And admittedly this is kind of tough situation to parse. 

So why not just create a shell script and call it `ipdb`: 

```bash
#!/bin/bash
/Users/amelio/anaconda/bin/ipython -c "%run -d $@"
```

and then when it prompts for a command that starts ipdb you have something easy to give it.

The other thing I do, is just start inside a shell and then run `realgud-track-mode`

**Comment by amelio-vazquez-reina** [comment]
Thanks. That worked great! 👍 I added the script to PATH and now everything works well.

For anyone using IPython, I found the combination of RealGUD with isend-mode](https://github.com/ffevotte/isend-mode.el) really useful:

* RealGUD: For debugging
* `isend-mode`: To send code from any buffer to an interpreter running on any buffer

The latter is helpful to grow code organically (i.e. run the debugger until you reach the portion of the code that you are working on, and then use `isend-mode` to test any _new_ code on the REPL)

**Comment by rocky** [comment]
Glad you got this working. I don't know that much about ipdb.

> For anyone using IPython, ...

Why not [add a page to the wiki](https://github.com/rocky/emacs-dbgr/wiki) with your suggestions? That way others will be able to learn from your wisdom. Thanks.

**Comment by cactail** [comment]
Hi everyone...
I did exactly every step that you suggested. I make the script and runs well on terminal also if I <code>import pdb</code> with <code>pdb.set_trace()</code> runs ipdb.
But from realgud, with: 

<code>M-x realgud:ipdb [RET]</code>
<code>Run ipdb (like this): ipdb /home/cactus/Dev/ownlibrary/play.py</code>

Then
<code>
Current directory: /home/cactus/Dev/ownlibrary/
Command: ipdb /home/cactus/Dev/ownlibrary/play.py
(file-error "Searching for program" "no existe el fichero o el directorio" "ipdb")
Failed to invoke debugger ipdb on program ipdb with args /home/cactus/Dev/ownlibrary/play.py
</code>

Sorry for post here, I should put a question on [Emacs StackExchange.com](http://emacs.stackexchange.com/)

**Comment by rocky** [comment]
The message says that GNU emacs can't find `ipdb`. What happens if you give an explicit path to whereever ipdb is located.

For example suppose it is inl `/usr/local/bin/ipdb`.  Then 

```
M-x realgud:ipdb [RET]
Run ipdb (like this): /usr/local/bin/ipdb /home/cactus/Dev/ownlibrary/play.py
```

**Comment by cactail** [comment]
Works! Great, thanks for the answer. Open a new buffer called *ipdb script.py shell*.
Why? Anyway to used only 
<code>Run ipdb (like this): ipdb some_file.py</code>

**Comment by rocky** [comment]
Since you can have several ipdb debugging sessions buffers have to have somewhat unique names.

I don't know if this answers your question because I don't understand your question.

**Comment by cactail** [comment]
Sorry. My question is, why I cannot write just
<code>Run ipdb (like this): ipdb /home/cactus/Dev/ownlibrary/play.py</code>
Why I have to write the absolute path to ipdb?

**Comment by cpitclaudel** [comment]
Does `ipdb` work in a terminal? If not, I'd guess ipdb is just not in your path.

**Comment by cactail** [comment]
Yes, it works in a terminal. For some reason, GNU Emacs can't find <code>ipdb</code> and only find it with absolute path.

**Comment by cpitclaudel** [comment]
@cactail You're not starting emacs from the terminal, are you? If so, then there's possibly a difference between the path that Emacs sees and the path that your terminal sees. Try `echo $PATH` in your shell and `M-: (getenv "PATH")` in Emacs.

**Comment by cactail** [comment]
You're right! My <code>ipdb</code> script was in <code>/home/cactus/.local/bin/</code>
I move it to <code>/usr/local/bin</code> when Emacs can see it. (There's a difference between path, like you said) and now works fine with <code>Run ipdb (like this): ipdb <path_to_python_file></code>.
Thank you for your answers!
